//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FALCONx.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FLCNX_DBEntities : DbContext
    {
        public FLCNX_DBEntities()
            : base("name=FLCNX_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<tUser> tUsers { get; set; }
        public virtual DbSet<tUserKey> tUserKeys { get; set; }
    
        public virtual int spUser_Delete(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUser_Delete", idParameter);
        }
    
        public virtual ObjectResult<spUser_Get_Result> spUser_Get(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUser_Get_Result>("spUser_Get", idParameter);
        }
    
        public virtual ObjectResult<spUser_GetAll_Result> spUser_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spUser_GetAll_Result>("spUser_GetAll");
        }
    
        public virtual int spUser_Insert(string firstName, string lastName)
        {
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUser_Insert", firstNameParameter, lastNameParameter);
        }
    
        public virtual int spUser_Update(Nullable<int> id, string firstName, string lastName)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUser_Update", idParameter, firstNameParameter, lastNameParameter);
        }
    }
}
