//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FALCONx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserImage
    {
        public string recNo { get; set; }
        public byte[] profile_picture { get; set; }
        public byte[] valid_id1 { get; set; }
        public byte[] valid_id2 { get; set; }
        public string userID { get; set; }
    }
}
