//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FALCONx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUserKey
    {
        public string keyID { get; set; }
        public string userID { get; set; }
        public string privateKey { get; set; }
        public string publicKey { get; set; }
        public Nullable<bool> revoked { get; set; }
        public Nullable<System.DateTime> dtCreated { get; set; }
        public Nullable<System.DateTime> dtModified { get; set; }
        public Nullable<System.DateTime> dtRevoked { get; set; }
        public Nullable<bool> accepted { get; set; }
    }
}
