//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FALCONx.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tUser
    {
        public string userID { get; set; }
        public string email { get; set; }
        public string given_name { get; set; }
        public string family_name { get; set; }
        public string middle_name { get; set; }
        public string company { get; set; }
        public string position { get; set; }
        public string mobile_number { get; set; }
        public string address { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string role { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string signature { get; set; }
    }
}
